/// World nationalities for autocomplete on the staff "Nationality" field.
/// UK/Ireland and the most common nationalities among UK nursery staff are
/// listed first so they surface immediately before the user even types.
const List<String> nationalities = [
  'British',
  'Irish',
  'Polish',
  'Romanian',
  'Portuguese',
  'Filipino',
  'Indian',
  'Nigerian',
  'Pakistani',
  'Bangladeshi',
  'Lithuanian',
  'Italian',
  'Spanish',
  'French',
  'German',
  'Bulgarian',
  'Somali',
  'Ghanaian',
  'South African',
  'Zimbabwean',
  'Kenyan',
  'Jamaican',
  'Brazilian',
  'Afghan',
  'Albanian',
  'Algerian',
  'American',
  'Argentinian',
  'Australian',
  'Austrian',
  'Belgian',
  'Bosnian',
  'Canadian',
  'Chinese',
  'Colombian',
  'Croatian',
  'Cypriot',
  'Czech',
  'Danish',
  'Dutch',
  'Egyptian',
  'Emirati',
  'Estonian',
  'Ethiopian',
  'Finnish',
  'Georgian',
  'Greek',
  'Hungarian',
  'Icelandic',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Israeli',
  'Ivorian',
  'Japanese',
  'Jordanian',
  'Kazakh',
  'Korean (South)',
  'Kosovan',
  'Kuwaiti',
  'Latvian',
  'Lebanese',
  'Libyan',
  'Malaysian',
  'Maltese',
  'Mexican',
  'Moldovan',
  'Moroccan',
  'Nepalese',
  'New Zealander',
  'Norwegian',
  'Peruvian',
  'Russian',
  'Rwandan',
  'Saudi Arabian',
  'Serbian',
  'Sierra Leonean',
  'Singaporean',
  'Slovak',
  'Slovenian',
  'Sri Lankan',
  'Sudanese',
  'Swedish',
  'Swiss',
  'Syrian',
  'Taiwanese',
  'Tanzanian',
  'Thai',
  'Tunisian',
  'Turkish',
  'Ugandan',
  'Ukrainian',
  'Uruguayan',
  'Venezuelan',
  'Vietnamese',
  'Yemeni',
  'Zambian',
];
