/// Major UK cities and towns, for autocomplete on the staff "City" field —
/// this is a UK-only marketplace (full app spec), so a curated local list
/// avoids both manual typing and a geocoding API dependency for this field.
const List<String> ukCities = [
  'London',
  'Birmingham',
  'Manchester',
  'Leeds',
  'Glasgow',
  'Sheffield',
  'Bradford',
  'Liverpool',
  'Edinburgh',
  'Bristol',
  'Cardiff',
  'Belfast',
  'Leicester',
  'Wakefield',
  'Coventry',
  'Nottingham',
  'Newcastle upon Tyne',
  'Sunderland',
  'Brighton',
  'Hull',
  'Plymouth',
  'Stoke-on-Trent',
  'Wolverhampton',
  'Derby',
  'Southampton',
  'Portsmouth',
  'York',
  'Peterborough',
  'Dundee',
  'Lancaster',
  'Oxford',
  'Cambridge',
  'Reading',
  'Luton',
  'Milton Keynes',
  'Northampton',
  'Norwich',
  'Swansea',
  'Aberdeen',
  'Bolton',
  'Bournemouth',
  'Middlesbrough',
  'Blackpool',
  'Ipswich',
  'Preston',
  'Newport',
  'Slough',
  'Telford',
  'St Albans',
  'Chelmsford',
  'Exeter',
  'Gloucester',
  'Southend-on-Sea',
  'Warrington',
  'Huddersfield',
  'Oldham',
  'Rotherham',
  'Blackburn',
  'Bury',
  'Stockport',
  'Colchester',
  'Poole',
  'Basildon',
  'Chester',
  'Watford',
  'Woking',
  'Guildford',
  'Maidstone',
  'Worthing',
  'Crawley',
  'Eastbourne',
  'Gillingham',
  'Rochester',
  'Dartford',
  'Basingstoke',
  'Cheltenham',
  'Worcester',
  'Hereford',
  'Shrewsbury',
  'Carlisle',
  'Lincoln',
  'Grimsby',
  'Scunthorpe',
  'Doncaster',
  'Barnsley',
  'Wigan',
  'St Helens',
  'Birkenhead',
  'Salford',
  'Solihull',
  'Dudley',
  'Walsall',
  'West Bromwich',
  'Redditch',
  'Kettering',
  'Corby',
  'Bedford',
  'Hemel Hempstead',
  'Stevenage',
  'Harlow',
  'High Wycombe',
  'Aylesbury',
  'Swindon',
  'Bath',
  'Taunton',
  'Yeovil',
  'Truro',
  'Torquay',
  'Weston-super-Mare',
  'Barnstaple',
  'Salisbury',
  'Winchester',
  'Chichester',
  'Hastings',
  'Tunbridge Wells',
  'Canterbury',
  'Margate',
  'Folkestone',
  'Ashford',
  'Stafford',
  'Crewe',
  'Nuneaton',
  'Rugby',
  'Loughborough',
  'Mansfield',
  'Chesterfield',
  'Halifax',
  'Harrogate',
  'Darlington',
  'Durham',
  'Gateshead',
  'South Shields',
  'Hartlepool',
  'Inverness',
  'Perth',
  'Stirling',
  'Paisley',
  'East Kilbride',
  'Livingston',
  'Kirkcaldy',
  'Ayr',
  'Wrexham',
  'Bangor',
  'Aberystwyth',
  'Merthyr Tydfil',
  'Neath',
  'Bridgend',
  'Londonderry',
  'Lisburn',
  'Newry',
  'Armagh',
  'Croydon',
  'Bromley',
  'Sutton',
  'Kingston upon Thames',
  'Enfield',
  'Barnet',
  'Harrow',
  'Ealing',
  'Hounslow',
  'Richmond upon Thames',
  'Greenwich',
  'Lewisham',
  'Wandsworth',
  'Hackney',
  'Islington',
  'Camden',
  'Westminster',
  'Tower Hamlets',
  'Newham',
  'Redbridge',
  'Havering',
  'Bexley',
  'Waltham Forest',
];
